FROM golang:1.14 AS build

WORKDIR /var/go/
RUN mkdir -p /root/.kube/
COPY api/go.mod go.mod
RUN go mod download

COPY api .

RUN go build -o /var/go/api ./cmd/api/main.go

ARG KUBECONFIG
COPY $KUBECONFIG /root/.kube/config.yaml
ARG K3D_CERT
COPY $K3D_CERT /usr/local/share/ca-certificates/k3d.crt
RUN update-ca-certificates

ENTRYPOINT /var/go/api
